-- US-NEPAL LEGAL SOLUTIONS - Full Database (for setup_full.php)
CREATE DATABASE IF NOT EXISTS us_nepal_legal_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE us_nepal_legal_db;

CREATE TABLE IF NOT EXISTS admins (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, full_name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_login TIMESTAMP NULL, is_active TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO admins (username, email, password, full_name) VALUES ('admin', 'admin@usnepallegal.com', '$2y$10$eqF05ovfu/oqXjr.Rqqi6.jHoVC90PibiLvUV/P1BKJWlL5AodB2K', 'Administrator');

CREATE TABLE IF NOT EXISTS admin_sessions (id INT AUTO_INCREMENT PRIMARY KEY, admin_id INT NOT NULL, session_token VARCHAR(255) NOT NULL UNIQUE, ip_address VARCHAR(45), user_agent TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL, FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE, INDEX idx_token (session_token), INDEX idx_admin (admin_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lawyers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, role VARCHAR(100) NOT NULL, focus TEXT, image_url VARCHAR(500), image_fit VARCHAR(20) DEFAULT 'cover', image_position VARCHAR(50) DEFAULT '50% 25%', bio TEXT, email VARCHAR(100), phone VARCHAR(20), education TEXT, experience TEXT, specializations TEXT, bar_associations TEXT, display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO lawyers (name, role, focus, image_url, display_order) VALUES ('Pradeep Thapa', 'Managing Partner', 'Energy, Hydropower, Aviation & FDI', 'https://images.unsplash.com/photo-1559548331-f9cb98001426?auto=format&fit=crop&w=800&q=80', 1),('Kedar Pyakurel', 'Principal Associate', 'Civil, Corporate & Writ Litigation', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80', 2),('Muktinath Acharya', 'Senior Associate', 'Property Law, Civil Law & Family Law', 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=800&q=80', 3);

INSERT INTO lawyers (name, role, focus, image_url, bio, email, phone, education, experience, specializations, bar_associations, display_order, is_active) VALUES ('Sudeep Pradhan', 'Associate', 'Banking & Finance, Corporate Advisory', 'https://images.unsplash.com/photo-1520975958225-3427ee9f5d64?auto=format&fit=crop&w=800&q=80', 'Sudeep supports lenders and borrowers across financing transactions.', 'sudeep.pradhan@usnepallegalsolutions.com', '+977-9800000004', 'LLM (Business Law), Kathmandu University', '6+ years advising on secured lending.', 'Banking & Finance, Corporate Governance', 'Nepal Bar Association', 4, 1),('Deepak Khanal', 'Associate', 'Tax, Compliance & Advisory', 'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?auto=format&fit=crop&w=800&q=80', 'Deepak advises clients on tax strategy.', 'deepak.khanal@usnepallegalsolutions.com', '+977-9800000005', 'LLB, Nepal Law Campus', '5+ years in tax advisory.', 'Tax Advisory, VAT/Customs', 'Nepal Bar Association', 5, 1),('Amit Kerna', 'Associate', 'Commercial Contracts', 'https://images.unsplash.com/photo-1520975686471-6c2d47f1a0c0?auto=format&fit=crop&w=800&q=80', 'Amit drafts commercial agreements.', 'amit.kerna@usnepallegalsolutions.com', '+977-9800000006', 'LLB, Kathmandu School of Law', '4+ years drafting contracts.', 'Commercial Contracts, Arbitration', 'Nepal Bar Association', 6, 1);

CREATE TABLE IF NOT EXISTS practice_areas (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(200) NOT NULL, text TEXT NOT NULL, icon_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS publications (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, text TEXT NOT NULL, image_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS client_logos (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(200) NOT NULL, image_url VARCHAR(500) NOT NULL, website_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS journals (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, image_url VARCHAR(500), description TEXT, display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS insights (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, text TEXT NOT NULL, image_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS hero_content (id INT AUTO_INCREMENT PRIMARY KEY, eyebrow_text VARCHAR(200), main_title VARCHAR(500), description TEXT, button_text VARCHAR(200), button_link VARCHAR(500), slider_interval_seconds INT DEFAULT 6, background_image_url VARCHAR(500), background_fit VARCHAR(20) DEFAULT 'cover', background_position VARCHAR(50) DEFAULT 'center', is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS hero_banners (id INT AUTO_INCREMENT PRIMARY KEY, eyebrow_text VARCHAR(200), main_title VARCHAR(500), description TEXT, button_text VARCHAR(200), button_link VARCHAR(500), background_image_url VARCHAR(500), background_fit VARCHAR(20) DEFAULT 'cover', background_position VARCHAR(50) DEFAULT 'center', display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS feature_strips (id INT AUTO_INCREMENT PRIMARY KEY, title TEXT NOT NULL, display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_settings (id INT AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(100) NOT NULL UNIQUE, setting_value TEXT, setting_type VARCHAR(50) DEFAULT 'text', updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS consultation_requests (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(200) NOT NULL, email VARCHAR(200) NOT NULL, phone VARCHAR(50) NOT NULL, appointment_date DATE NULL, appointment_time TIME NULL, about VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_created (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS about_content (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, text TEXT NOT NULL, image_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS consultation_fees (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, text TEXT NOT NULL, display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS why_choose_us (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, text TEXT NOT NULL, display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS articles (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(300) NOT NULL, description TEXT, text TEXT, image_url VARCHAR(500), display_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_active (is_active), INDEX idx_order (display_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO hero_banners (eyebrow_text, main_title, description, button_text, button_link, background_image_url, display_order, is_active) VALUES ('Experience Matters', 'Serving with 100 Years\nof Combined Expertise', 'Our lawyers offer clients a range of integrated global capabilities.', 'WHY CLIENTS CHOOSE US? →', '/#about', 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1800&q=80', 1, 1),('Trusted Advisors', 'Full-Service Legal\nSolutions in Nepal', 'We support businesses and individuals with clear, practical advice.', 'Explore Practice Areas →', '/#practice', 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1800&q=80', 2, 1),('Client First', 'Professional Legal\nRepresentation', 'A team of recognized lawyers delivering effective legal services.', 'Meet Our Lawyers →', '/lawyers', 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=80', 3, 1) ON DUPLICATE KEY UPDATE id=id;

INSERT INTO about_content (title, text, image_url, display_order, is_active) VALUES ('About US-NEPAL LEGAL SOLUTIONS', 'US-NEPAL LEGAL SOLUTIONS is a full-service law firm in Nepal delivering trusted legal counsel across corporate advisory, litigation, banking & finance, aviation, and foreign investment.', 'https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=1400&q=80', 1, 1) ON DUPLICATE KEY UPDATE id=id;

INSERT INTO site_settings (setting_key, setting_value, setting_type) VALUES ('site_name', 'US-NEPAL LEGAL SOLUTIONS', 'text'),('site_tagline', 'LEGAL SOLUTIONS', 'text'),('favicon_url', '/favicon.svg', 'url'),('contact_email', 'info@usnepallegalsolutions.com', 'text'),('contact_phone', '+1 (785) 506-3402', 'text'),('contact_address', 'Anamnagar, Kathmandu', 'text'),('footer_background_image_url', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80', 'url') ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), setting_type = VALUES(setting_type);

INSERT INTO practice_areas (title, text, display_order) VALUES ('Arbitration & Dispute Resolution', 'US-NEPAL LEGAL SOLUTIONS has highly trained lawyers in Arbitration.', 1),('Aviation Law', 'The Firm specializes in aircraft registration, airworthiness, flight operations.', 2),('Due Diligence', 'US-NEPAL LEGAL SOLUTIONS has a dedicated group of investigators.', 3),('Employment & Labor Law', 'US-NEPAL LEGAL SOLUTIONS deals in labor and employment contracts.', 4),('Foreign Direct Investment (FDI)', 'Our Corporate Firm provides assistance to foreign companies.', 5),('Hydropower Law', 'The Firm has engaged in obtaining approvals for hydropower projects.', 6),('Civil & Corporate Litigation', 'We offer litigation services across civil, criminal, and corporate domains.', 7),('Tax Law', 'We offer broad service in all aspects of tax law.', 8),('Telecommunications Law', 'US-NEPAL LEGAL SOLUTIONS assists in registration and licensing.', 9);

INSERT INTO publications (title, text, image_url, display_order) VALUES ('FDI in Telecommunication Sector in Nepal', 'Foreign Direct Investment has become a major driver of Nepal telecommunication growth.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=80', 1),('FDI in Vehicle Manufacturing in Nepal', 'FDI in Nepal vehicle manufacturing sector offers big opportunities.', 'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=80', 2),('FDI in Cargo and Logistics Sector', 'FDI in Nepal cargo and logistics industry drives growth.', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80', 3);

INSERT INTO client_logos (name, image_url, display_order) VALUES ('Himalayan Capital', 'https://dummyimage.com/160x60/ffffff/1f5e2e&text=Himalayan+Capital', 1),('Tibet Airlines', 'https://dummyimage.com/160x60/ffffff/1f5e2e&text=Tibet+Airlines', 2),('Bishwa Airways', 'https://dummyimage.com/160x60/ffffff/1f5e2e&text=Bishwa+Airways', 3),('Malaysia Airlines', 'https://dummyimage.com/160x60/ffffff/1f5e2e&text=Malaysia+Airlines', 4),('Frojob', 'https://dummyimage.com/160x60/ffffff/1f5e2e&text=Frojob', 5);

INSERT INTO journals (title, image_url, display_order) VALUES ('Nepalese Aviation Law & Regulation', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80', 1),('Consumer Court & Its Jurisdiction', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=600&q=80', 2),('Prospects of FDI in Nepal', 'https://images.unsplash.com/photo-1500534314209-a26db0f5c4b8?auto=format&fit=crop&w=600&q=80', 3);

INSERT INTO insights (title, text, display_order) VALUES ('Process of Company Registration in Nepal', 'The Firm has researched the latest processes for incorporating a business in Nepal.', 1),('Court Marriage in Nepal: Requirements & Process', 'The requirements and procedures for Court Marriage in Nepal.', 2),('Divorce Process in Nepal: New Divorce Law', 'Latest insights into conducting Divorce in Nepal.', 3);

INSERT INTO hero_content (eyebrow_text, main_title, description, button_text, button_link, background_image_url, is_active) VALUES ('Experience Matters', 'Serving with 100 Years\nof Combined Expertise', 'Our lawyers offer clients a range of integrated global capabilities.', 'WHY CLIENTS CHOOSE US? →', '#', 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80', 1);

INSERT INTO feature_strips (title, display_order) VALUES ('Leading Law Firm in Nepal providing complete Legal Solutions', 1),('US-NEPAL LEGAL SOLUTIONS | Law Firm in Nepal | Lawyers in Nepal', 2),('Team of Recognized Lawyers with 100 Years of Experience', 3);
